### ISSUE TITLE
Android Mockups

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#1]
We need mockups for our initial design based on the specifications distributed to the team.

**Comment by satya164** [comment]
![glucosio-start](https://cloud.githubusercontent.com/assets/1174278/9152178/978a46f0-3e3b-11e5-9597-ff574cc661d9.png)
![glucosio-blankslate](https://cloud.githubusercontent.com/assets/1174278/9152179/9a7ebeea-3e3b-11e5-9513-4d531579eca2.png)
![glucosio-add](https://cloud.githubusercontent.com/assets/1174278/9152180/a0aa366e-3e3b-11e5-8ed3-e3c61f1c2a0b.png)
![glucosio-overview](https://cloud.githubusercontent.com/assets/1174278/9152181/ab4852ae-3e3b-11e5-8252-0fb399cd3453.png)

**Comment by PaoloRotolo** [comment]
![photo_2015-08-15_09-57-43](https://cloud.githubusercontent.com/assets/5623301/9354737/48185054-4673-11e5-9fb6-2bab563e1dc6.jpg)

**Comment by bkerensa** [comment]
If these are all finals? let me know I am going to move some of this to wiki

**Comment by satya164** [comment]
![0-glucosio-start 2x](https://cloud.githubusercontent.com/assets/1174278/9427814/997ec5c6-49ad-11e5-9cdd-11014b8e700e.png)
![1-glucosio-blankslate 2x](https://cloud.githubusercontent.com/assets/1174278/9427815/9984898e-49ad-11e5-8b9a-f665ef1fc126.png)
![2-glucosio-add 2x](https://cloud.githubusercontent.com/assets/1174278/9427816/998977aa-49ad-11e5-96eb-82bd70d2e06f.png)
![3-glucosio-overview 2x](https://cloud.githubusercontent.com/assets/1174278/9427817/998a11c4-49ad-11e5-889b-bb87cc2653d6.png)
![4-glucosio-history 2x](https://cloud.githubusercontent.com/assets/1174278/9427819/99904e86-49ad-11e5-8313-e537cecb85d4.png)
![5-glucosio-tips 2x](https://cloud.githubusercontent.com/assets/1174278/9427818/998f1cb4-49ad-11e5-8c0c-c4fe77222787.png)

**Comment by bkerensa** [comment]
@PaoloRotolo anything left here?

**Comment by PaoloRotolo** [comment]
We still need mockups for Settings. There's another issue opened though.

**Comment by bkerensa** [comment]
I will close this then and we can track in the settings issue and the tips issue I think thats the remaining issues.
