### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [Glucosio/android#103]
A thread for its inclusion has been created at https://f-droid.org/forums/topic/glucosio/

**Comment by bkerensa** [comment]
We are investigating inclusion in F-Droid

**Comment by PaoloRotolo** [comment]
Done. It's live here: https://f-droid.org/repository/browse/?fdfilter=glucosio&fdid=org.glucosio.android

**Comment by pizzamaker** [comment]
Thanks!

**Comment by bkerensa** [comment]
@pizzamaker one thing I would add is the version on F-Droid is wrong the source you are building from is 0.8.0.
