### ISSUE TITLE
Editing mmol/L unit values in dialog shows value in mg/dL (wrong units)

### ISSUE THREAD

**Issue by chwalters** [Glucosio/android#123]
Set unit preference to mmol/L, add new reading works ok, shows fine in the history list, but when long-press to edit a historic value I'm getting the mg/dL value in the dialog even though unit for the field is mmol/L.  The value in edit dialog isn't converted for display/editing, even if the dialog shows the right units in the label

**Comment by PaoloRotolo** [comment]
Fixed in commit 296021bc1ec3f530269176480da989fffa670122.
