### ISSUE TITLE
Hello View

### ISSUE THREAD

**Issue by PaoloRotolo** [Glucosio/android#13]
Add Hello View to ask more information about user on first start.

![0-glucosio-start](https://cloud.githubusercontent.com/assets/1174278/9290516/3e05cacc-43b4-11e5-9c65-3adf695ad096.png)

**Comment by bkerensa** [comment]
@PaoloRotolo On this we are going to delay right so I can provide additional fields and @satya164 can provide an updated mockup?

**Comment by bkerensa** [comment]
If so I can have fields copy by tomorrow afternoon PST

**Comment by PaoloRotolo** [comment]
Right, we need **Name, Country, Age, Gender, Height, Weight, Ethnicity, Email**.
And eventually a button with **data policy** under "share data for research".

**Comment by satya164** [comment]
Do we need **Country**, **Ethnicity**, **Email** in the first start screen? They are not necessary to get started with the app, and not necessary to use the app either.

We can have a tip asking for these info and explaining why, as @PaoloRotolo suggested, at a later time when using the user is actively using the app.

About **Weight**, it's a variable. It will change from time to time, and it's is not a setting either. We need to think how do we handle that.

**Age** is also a variable, but it's predictable. Probably what we need is the birth date, so we always know the correct age. Or may be we don't, approximate age should be fine, right? We could just store the date on which the user entered his/her age, and determine the approximate age from that. We could have option to set birth date. But it shouldn't be a strict necessity.

**Comment by PaoloRotolo** [comment]
@satya164 can we add Diabetes type (1 - 2) at least?

**Comment by satya164** [comment]
![0-glucosio-start](https://cloud.githubusercontent.com/assets/1174278/9427602/2314dea6-49a4-11e5-8f88-3d39b6340279.png)

**Comment by satya164** [comment]
![0-glucosio-start](https://cloud.githubusercontent.com/assets/1174278/9427608/53f533d6-49a4-11e5-9581-a598d204a33b.png)

**Comment by bkerensa** [comment]
@satya164 @PaoloRotolo just above opt in can we put a check mark and link to our terms of use?

**Comment by bkerensa** [comment]
Specifically the medical disclaimer that covers us legally

**Comment by satya164** [comment]
@bkerensa There is a question mark icon

**Comment by bkerensa** [comment]
@satya164 No I am saying can we add another check box to confirm user has read terms of use in regards to the whole app. It would be a slightly longer version of this http://www.glucosio.org/disclaimer/

**Comment by satya164** [comment]
Hmm. Will figure out how to put that then.

**Comment by PaoloRotolo** [comment]
@satya164 any update?

**Comment by satya164** [comment]
Most probably it'll be the next screen after this, in which there will be a short summary for the license with option to read the full license. Will work with @priynag to settle on it

**Comment by bkerensa** [comment]
Any update on this one?

**Comment by satya164** [comment]
Working with @priynag on this

**Comment by bkerensa** [comment]
@PaoloRotolo @satya164 Reminder: String Freeze is six days from today please wrap up open issues for this release.

**Comment by satya164** [comment]
![0 0-glucosio-start](https://cloud.githubusercontent.com/assets/1174278/9800528/0d1d5282-582b-11e5-871e-06cb6a7bc599.png)
![0 1-glucosio-disclaimer](https://cloud.githubusercontent.com/assets/1174278/9800529/0d22a124-582b-11e5-9874-eccf1500c3cd.png)

**Comment by bkerensa** [comment]
Bravo

**Comment by bkerensa** [comment]
@satya164 that works perfect the 1 hello view followed up by the terms of use view

**Comment by bkerensa** [comment]
@PaoloRotolo  I think this is over to you now?

**Comment by PaoloRotolo** [comment]
Yes, I'm pushing the new view.

**Comment by elioqoshi** [comment]
Great, thanks guys for this!

**Comment by satya164** [comment]
We should work on making the hello view fit within the screen. At least medium size 5" screens. Reducing the spacing between the elements will help a lot. The app has too much spacing compared the mockup.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?

**Comment by elioqoshi** [comment]
Do you need advice on this?

**Comment by bkerensa** [comment]
I think this is done.

@PaoloRotolo can you confirm?

**Comment by PaoloRotolo** [comment]
Yes, I've reduced the padding and made the view fit perfectly.

![screenshot from 2015-10-01 21-24-41](https://cloud.githubusercontent.com/assets/5623301/10231424/f02bc862-6882-11e5-8d9d-9b1b0441e998.png)
 a 5'' screen.
