### ISSUE TITLE
Brand assets for Glucosio

### ISSUE THREAD

**Issue by birajkarmakar** [Glucosio/android#132]
@elioqoshi 

It would be good to have below things

1. Glucat in png format
2. Logo in png format
3. High resolution background 
4. Some high resolution screenshot

**Comment by elioqoshi** [comment]
why did you close this @bkerensa ?

**Comment by birajkarmakar** [comment]
Hi @elioqoshi I opened this issue in wrong part unknowingly. 

That's why it has been closed. 

But @bkerensa has opened this request under brand-assets.

**Comment by PaoloRotolo** [comment]
He moved it to Glucosio/brand-assets: https://github.com/Glucosio/brand-assets/issues/4
