### ISSUE TITLE
Weekly average calculation is incorrect when there is data for less than a week

### ISSUE THREAD

**Issue by lgp171188** [Glucosio/android#136]
For example there some ``n`` readings within a week and there is no data for at least a week, the weekly average calculation takes the first reading as the average since it counts the number of weeks as 0. Instead number of weeks should always start from one and show correct the average for the current incomplete week.

I will try to fix this and submit a pull request.

**Comment by lgp171188** [comment]
Fixed in 0cc657d237a9b8c074e07b95888ab38a9b0ab02b

**Comment by PaoloRotolo** [comment]
Thanks again! :+1:
