### ISSUE TITLE
App Intro

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#17]

**Comment by PaoloRotolo** [comment]
@bkerensa We need text and images for the slides.

**Comment by bkerensa** [comment]
Can you provide me slides so I can narrate properly

**Comment by bkerensa** [comment]
@PaoloRotolo ?

**Comment by satya164** [comment]
We don't need a separate app into view, we already have a hello view (2 pages), we can just add one more page. No need to make the first start longer than it needs to be.

**Comment by bkerensa** [comment]
Ok closing this then
