### ISSUE TITLE
Design inconsistencies and bugs in current APK

### ISSUE THREAD

**Issue by satya164** [Glucosio/android#19]
- [x] Spacing should be even on all 4 sides, there is too less space at top and way too much at bottom
- [x] The buttons don't behave like buttons, basically they don't have any padding around them and hence the touch effect isn't visible at all
- [x] Also, dialog shouldn't be full width
- [x] In the dialog, I'm entering details at night, and it still says "Before breakfast" under "Measured"
- [x] In the history panel, there is way too much shadow below the items
- [x] The history items should be categorized by day
- [x] The language should be pre-filled from system language if translations are available, otherwise english
- [x] The time should be like "11:36 pm" or "23:36", according to system preferences
- [x] The date should be formatted like "Tuesday, 1st September 2015" or similar human readable format
- [x] The concentration amount should include the unit.
- [x] Concentration amounts throughout the shouldn't be decimal, coz we don't allow entering decimal points, hence no use of showing it
- [x] Amount should be orange if it goes above the average conc.
- [x] The number below it should indicate how much does it fluctuate from average
- [x] In the snackbar which appears on deleting an item, should have yellow text, not pink
- [x] There seems to some empty space below the snackbar
- [x] The background of history cards should be white
- [x] The design of tips cards should be similar to history cards, e.g. - full width separators, white backgrounds
- [x] The line height should be at least 1.5 for all paragraphs, paragraph spacing should be .75, e.g. - for 16dp, line height will be 24dp, and paragraph spacing will be 12dp.
- [x] On scrolling, the titlebar and tabs should move up and the titlebar should hide
- [x] Switching tabs seems to be unreliable, sometimes tapping on a tab does nothing. e.g. - Open app > Swipe 2 times to go to TIPS > Tap on OVERVIEW (doesn't work)
- [x] If the design of the graph could be closer to the mockup, it would be better, especially the numbers on x and y axes. Basically, instead of writing the date on x-axis, it can be the heading, and x-axis can have the time only in bigger font. y-axis can get rid of decimal places, and can have bigger fonts
- [x] In the overview mode, as well as everywhere else, separators should be full width
- [x] Currently tips don't have a title, also try adding some tips which have actions, like update weight, set reminder etc.
- [x] The tips tab should have a badge indicating number of tips
- [x] In "Hello view", the button doesn't have any effect of tap (ripple/highlight)
- [x] In "Hello view", the button should have an icon on it's right (chevron-right)

**Comment by PaoloRotolo** [comment]
- The number below it should indicate how much does it fluctuate from average:
Me and @bkerensa decided to remove the number because it's difficult to say what's the perfect average of glucose for each person.

- Currently tips don't have a title [...]
@bkerensa do we need titles? If yes, can you update the wiki page?
http://wiki.glucosio.org/Planning/tips_activity

Also graph design is something complicated, I'll try to improve something but I guess we can't have it like the mockup...

**Comment by satya164** [comment]
Hmm... I meant, average as in the average readings of that person. Not best readings.

Can we have bigger fonts and remove the date from every item in x-axis? It's redundant and take lots of space. But let's see what's possible.

**Comment by bkerensa** [comment]
Could we have a colored blood drop thats either Green Yellow or Red as they enter the the reading? It can use the target range they set during Hello to gauge whether they are in a healthy range in the middle or bad.

**Comment by PaoloRotolo** [comment]
@satya164 what about colored blood drop in history? (↑)

**Comment by bkerensa** [comment]
No titles needed

**Comment by satya164** [comment]
@bkerensa titles help look at the tips at a glance. Also, say we have some tips which are too long, the description can be cut off and user will need to go to full view to read it (I'll mock it up).

Also, aesthetically, plain paragraphs of text don't look very pleasing without any headings and not glancable.

I had this in mind

* title -> do something
* summary -> why to do it and how
* action -> click to do it

**Comment by satya164** [comment]
@paolorotolo the color of the value already indicates that.

And about using a drop, it won't look like a blood drop anymore as color will change (more like a drop of medicine). But lemme check if it looks good or like too noisy (lots of pointed ends)

**Comment by PaoloRotolo** [comment]
"Switching tabs seems to be unreliable" was a bug in Google's library. Fixed it updating to Android Design Library 23.0.1 (commit 1c10b8f23d636e0140a51c91649d34170fa6c0fd).

**Comment by bkerensa** [comment]
@paolorotolo how are we on this list?

**Comment by bkerensa** [comment]
@PaoloRotolo @satya164  Reminder: String Freeze is six days from today please wrap up open issues for this release.

**Comment by bkerensa** [comment]
@PaoloRotolo How is progress on these remaining bits?

**Comment by bkerensa** [comment]
@PaoloRotolo anything left here? if not close

**Comment by PaoloRotolo** [comment]
Forgot to close this :\ Thanks.

**Comment by satya164** [comment]
@PaoloRotolo There are items on the list which are not complete

**Comment by bkerensa** [comment]
Marking remaining for 0.8.1
