### ISSUE TITLE
Make sure UI scales 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#23]
We need to make sure our UI will scale to translated words as they may be larger than the UI is currently intended for instance overview translated to spanish is longer and so its tips.

Note from Mozilla's l10n lead staff:
Since they're translating strings out of context, they'll need to be able to test them within a build to ensure that the meaning is accurately represented in the translation, that the app is properly internationalized, and that their translations fit within the UI constraints of both a mobile device

**Comment by bkerensa** [comment]
@PaoloRotolo Reminder: String Freeze is six days from today please wrap up open issues for this release.

**Comment by bkerensa** [comment]
@PaoloRotolo have you tested on tablet at all?

**Comment by PaoloRotolo** [comment]
Yes, UI scales correctly on tablets too.
