### ISSUE TITLE
Translation Test Builds

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#24]
We will need to get a final build to our translators before we release so they can test their translations in the UI and make sure the context works.

Note from Mozilla's l10n lead staff:
Since they're translating strings out of context, they'll need to be able to test them within a build to ensure that the meaning is accurately represented in the translation, that the app is properly internationalized, and that their translations fit within the UI constraints of both a mobile device

**Comment by bkerensa** [comment]
I will coordinate this with Arturo

**Comment by PaoloRotolo** [comment]
All translations are now working. Just change your system language to see the changes :)

To convert translations exported from the website to Android format use:
``` rename s/'^'/'values-'/ * && find . -type d -name Android -exec bash -c 'cd {} && mv *xml ../' \;```

**Comment by bkerensa** [comment]
We will get final builds out on the 15th for testers to QA all translations
