### ISSUE TITLE
Ensure Database Scales to Long Term Needs

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#25]
In discussion with Paolo and Christopher it seems obvious that the database will need some changes to ensure it can scale to the kind of data we will be handling long term.

Lets identify with Christopher what changes he thinks are best and either he or @ahhmarr can implement them.

Paolo I will assign this to you can we get Christopher's email on Telegram and I can invite him so we can maybe assign to him. We have a very short window to release so lets push on this.

**Comment by PaoloRotolo** [comment]
@ahhmarr, @chrispecoraro, can you work on this?

**Comment by bkerensa** [comment]
Lets use this as a meta tracker for optimizations specifically one thing we need to address in Noce is adding a ORM see issue #55 if we do not it will cause future issues. ORMlite seems to be one option but there may be better options too.
