### ISSUE TITLE
Application Settings 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#3]
For our initial release we will want users to be able to:
Set Demographics (Age, Gender, Language, Country, City)
Set Measurements mmol/L or mg/dl 
Opt-In to Academic Research (Although backend wont be live till future version)
Input Category Customization (Measure before bed, after meal, fasting etc)
Notification Settings (Hourly, Daily or other interval reminders to input Glucose)

**Comment by bkerensa** [comment]
@satya164 ping

**Comment by satya164** [comment]
@bkerensa on it.

**Comment by bkerensa** [comment]
:fist:

**Comment by bkerensa** [comment]
@PaoloRotolo @satya164 Looks like this is our biggest final blocker for this release lets try and close this if we can by friday?

**Comment by satya164** [comment]
We don't have mauch settings right now, so we can just use a basic preferences view. We can add more categories as the number of items grow.

Things we need in settings,

1. Language
2. Age
3. Gender
4. Height
5. Weight
6. Diabetes type
7. Preferred unit
8. Version
9. Terms of usage
10. Feedback
11. Open Source Licenses
12. ???

![7-glucosio-preferences](https://cloud.githubusercontent.com/assets/1174278/9801000/f65fbc4e-582d-11e5-9e43-e2ec541c594e.png)

**Comment by bkerensa** [comment]
@satya164  Yes we should also have a date and time setting so people can have locale based data and time picker versus defaulting to European. There should be a checker in Hello that checks this value on first open but also users should be able to change the setting under settings too in case something happens wrong.

**Comment by PaoloRotolo** [comment]
@bkerensa @satya164 do we really need Language and Date format?
We can just take the value from local Android preferences. Not doing that means override a lot of code to ignore system's language...

**Comment by bkerensa** [comment]
Fine let's detect the language from locale but can we do that with country? This also means we will have to change Hello.

And what do we do for l10n then? Like if a language is unavailable can it default to English of we don't have 100% translated?

**Comment by PaoloRotolo** [comment]
In HelloActivity I think we should ask for Country, not Language.

**Comment by PaoloRotolo** [comment]
Settings are working in latest commit. Closing.

**Comment by satya164** [comment]
In the settings dialogs, the radio button which represents the current value should be checked. Currently nothing is checked.

Things which are very large, like Terms of usage, should open in a new page rather than a dialog.

The country selection should be a page, and should have search. Check `System Settings > Language & input > Language` to have an idea about the design.

**Comment by PaoloRotolo** [comment]
@satya164 I've fixed the first bug in latest commit.
About country selection, user will not change his country a lot of times. Also because HelloView automatically selects user country based on Locale. I guess we can implement a customized view later (0.9.0 or 0.8.1).

**Comment by bkerensa** [comment]
FYI for me its not auto selecting country it picks Afghanistan by default.

**Comment by PaoloRotolo** [comment]
Try to install daily again. I fixed that in latest commit.

**Comment by satya164** [comment]
@paolorotolo I still think we should change it. In projects small things like this get postponed, and they are never done, coz there are always new things to do. So I would say, don't compromise on design just because it's not frequently used. Yes, it's not frequently used, but when it is, it's a real pain to use it.

**Comment by satya164** [comment]
Also, there is a green button (?) in the country selection dialog.

**Comment by satya164** [comment]
Also, the new terms of use page, it should be just like any other page, actionbar with back button with the title, and the content should be a scrollview with the license. The OK button doesn't have any meaning and is unnecessary.

Also, content is cut off at bottom, and no momentum scroll.

**Comment by PaoloRotolo** [comment]
Ok, @satya164 can you give me a .svg file of the curved line?

**Comment by satya164** [comment]
I'm on mobile now. Will give you tomorrow. Or may be ask @elio if he can do a fancy arrow.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?

**Comment by dmvstar** [comment]
settings additions.
Insulin or other medications - the type, dose and time of reception

**Comment by bkerensa** [comment]
@dmvstar This should be a separate bug we will add that to Imli our next release but it wont make this release. I'll go ahead and file that!

**Comment by PaoloRotolo** [comment]
Closing for now.
Please open a new issue for dedicated Languages activity and tag it as Enhancement.
