### ISSUE TITLE
"Get Started" button on Welcome screen is not viewable.

### ISSUE THREAD

**Issue by chrispecoraro** [Glucosio/android#33]
On my device, Samsung Galaxy S5, "Get Starting" is not viewable without scrolling.

**Comment by bkerensa** [comment]
We need to try and figure this out I will test on Nexus 5 later today when my fiancee gets home
lets also get some others with other devices to test and make sure were not missing something.

**Comment by satya164** [comment]
Another issue is, the absence of scrollbars in scrollviews.

**Comment by bkerensa** [comment]
Should we need scrollbars in Hello? ideally it should be viewable without any scrolling?

**Comment by bkerensa** [comment]
@PaoloRotolo Have we done everything on this checklist? http://developer.android.com/training/multiscreen/screensizes.html

**Comment by satya164** [comment]
@bkerensa Yeah, but we need scrollbars in very small screens. For example, my phone screen isn't that small, so we can tweak the showing etc so that it doesn't need scrollbars. But we can't do anything for very small screens.

**Comment by bkerensa** [comment]
@satya164 I see ok well lets have @PaoloRotolo look into adding that and see if we can determine why @chrispecoraro's isnt showing right since he has a decent sized screen.

Also have we any covered for tablet? Do we know how it displays?

**Comment by PaoloRotolo** [comment]
Fixed. See #13.
