### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#4]
We will want a dedicated graph view/activity powered perhaps by https://github.com/PhilJay/MPAndroidChart or another library that @PaoloRotolo finds suitable. 

Additionally we may want to consider having the main view or main activity be a sort of dashboard that shows some smaller graphs and data see the blow example:
![mainpage](https://cloud.githubusercontent.com/assets/859175/9090272/22dcc160-3b4e-11e5-821b-baa66fa9d11d.png)

I like the main screen idea but theirs is kind of busy and we can do better on layout and design.

**Comment by bkerensa** [comment]
@PaoloRotolo Any graph <3 to share yet?

**Comment by PaoloRotolo** [comment]
@bkerensa yes, well, almost ready
![screenshot from 2015-08-23 19-44-21](https://cloud.githubusercontent.com/assets/5623301/9429436/14e06fea-49d0-11e5-929f-0f948af187ff.png)
![screenshot from 2015-08-23 19-44-11](https://cloud.githubusercontent.com/assets/5623301/9429437/14e293c4-49d0-11e5-8efe-7c87f2618d27.png)

 :D

**Comment by bkerensa** [comment]
@PaoloRotolo Are we done with all graph work for this release?

**Comment by PaoloRotolo** [comment]
Yes, the graph is up and working. We can close.
