### ISSUE TITLE
Add Glucosio icon above tabs

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#45]
We should consider having the glucosio icon in the top lefthand side of the app above tabs

https://github.com/Glucosio/brand-assets/blob/master/logos/png/PNG-07.png

**Comment by bkerensa** [comment]
@elioqoshi eh?

**Comment by satya164** [comment]
What problem does this solve? The user already clicked on the app icon to go into the app, and he/she will always know how our logo looks like. We don't need to constantly remind it to the user.

To add, the guidelines doing recommend it either. It's just an unnecessary element serving no purpose.

**Comment by PaoloRotolo** [comment]
Ok, I'm going to close this. Google Design guidelines doesn't recommend to add an icon above tabs.

**Comment by elioqoshi** [comment]
I'd be up to put the Wordmark instead of the Glucosio text which is written in the native Android font

**Comment by bkerensa** [comment]
@PaoloRotolo Can you make this so? :)

**Comment by PaoloRotolo** [comment]
Sounds good. I'm on it :)

**Comment by PaoloRotolo** [comment]
Before and after.

![screenshot from 2015-09-17 21-54-13](https://cloud.githubusercontent.com/assets/5623301/9944321/c2c43910-5d86-11e5-933a-a5f3e0569bea.png)

![screenshot from 2015-09-17 21-54-46](https://cloud.githubusercontent.com/assets/5623301/9944320/c2c4257e-5d86-11e5-905e-9498d7b2f079.png)

**Comment by elioqoshi** [comment]
@PaoloRotolo Perfect! Thank you!
