### ISSUE TITLE
Input View

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#5]
an area dedicated to inputting glucose levels including level and picking a category such as fasting input, after meal, feeling sick, or a specific meal time.

See example of other apps input view 
![input](https://cloud.githubusercontent.com/assets/859175/9090309/581172c2-3b4e-11e5-9533-f9fd85e101a1.png)
![unnamed2](https://cloud.githubusercontent.com/assets/859175/9090318/62d69e8a-3b4e-11e5-900d-0f782fff4ecd.png)

**Comment by bkerensa** [comment]
@PaoloRotolo do we have an updated mockup for this view?

**Comment by satya164** [comment]
![2-glucosio-add](https://cloud.githubusercontent.com/assets/1174278/9427799/086438fa-49ad-11e5-9a45-bfafe343270a.png)

**Comment by PaoloRotolo** [comment]
Input view is working great right now. I think we can close.

**Comment by bkerensa** [comment]
See issue #44 we need to clear that bug out and then ensure Input View supports those changes

**Comment by PaoloRotolo** [comment]
Closing again.

**Comment by bkerensa** [comment]
@PaoloRotolo have you finished all input view work for noce?

**Comment by PaoloRotolo** [comment]
yes, custom categories are working.
