### ISSUE TITLE
Glucat Mascot

### ISSUE THREAD

**Issue by elioqoshi** [Glucosio/android#57]
I worked a bit on the Glucat mascot today on my own. I'm pretty satisfied honestly. What do you think?
![glucat-01](https://cloud.githubusercontent.com/assets/5436686/9965743/a680fda8-5e38-11e5-82dc-617e86565022.jpg)
![glucat-02](https://cloud.githubusercontent.com/assets/5436686/9965744/a681afd2-5e38-11e5-99f4-628e89b9b8c3.jpg)

**Comment by elioqoshi** [comment]
![facebook banner pink-01](https://cloud.githubusercontent.com/assets/5436686/9966037/a2413f9e-5e3a-11e5-8cfc-8a35de96195e.jpg)
![facebook banner white-01](https://cloud.githubusercontent.com/assets/5436686/9966038/a242682e-5e3a-11e5-8a14-d01e4e33f95d.jpg)

Facebook Banners!

I think we have wrapped this up. Comments?

**Comment by bkerensa** [comment]
Looks great
