### ISSUE TITLE
About View

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#6]
About (view) to list licensing information of the app and of open source libraries used and with a short paragraph about the project and current version of the app being ran. We could also have a link to our website, github etc here.

**Comment by bkerensa** [comment]
@satya164 @PaoloRotolo do we have a mockup for this view yet?

**Comment by PaoloRotolo** [comment]
Nope. @satya164 ?

**Comment by satya164** [comment]
I'll mock something up

**Comment by satya164** [comment]
I looked at few apps, and they all put the about info in preferences. May be we can do the same.

**Comment by bkerensa** [comment]
Can you show an example?

**Comment by satya164** [comment]
![screenshot_2015-08-23-15-37-12](https://cloud.githubusercontent.com/assets/1174278/9427793/8e382546-49ac-11e5-8e09-1f4acdadef81.png)

**Comment by bkerensa** [comment]
That works

**Comment by bkerensa** [comment]
@PaoloRotolo @satya164 Reminder: String Freeze is six days from today please wrap up open issues for this release.

**Comment by PaoloRotolo** [comment]
@satya164 @elioqoshi @bkerensa Can we close? It seems we're adding info in settings.
