### ISSUE TITLE
java.lang.IllegalStateException: ActionBarContextView can only be used with android:layout_width="match_parent" (or fill_parent)

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#62]
Using testobject to spam the UI I was able to crash Glucosio with the following exception:
13:32:37 E AndroidRuntime : FATAL EXCEPTION: main
13:32:37 E AndroidRuntime : Process: org.glucosio.android, PID: 27326
13:32:37 E AndroidRuntime : java.lang.IllegalStateException: ActionBarContextView can only be used with android:layout_width="match_parent" (or fill_parent)
13:32:37 E AndroidRuntime : at com.android.internal.widget.ActionBarContextView.onMeasure(ActionBarContextView.java:339)
13:32:37 E AndroidRuntime : at android.view.View.measure(View.java:17547)
13:32:37 E AndroidRuntime : at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
13:32:37 E AndroidRuntime : at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
13:32:37 E AndroidRuntime : at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
13:32:37 E AndroidRuntime : at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
13:32:37 E AndroidRuntime : at android.view.View.measure(View.java:17547)
13:32:37 E AndroidRuntime : at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
13:32:37 E AndroidRuntime : at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
13:32:37 E AndroidRuntime : at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
13:32:37 E AndroidRuntime : at android.view.View.measure(View.java:17547)
13:32:37 E AndroidRuntime : at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
13:32:37 E AndroidRuntime : at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1148)
13:32:37 E AndroidRuntime : at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
13:32:37 E AndroidRuntime : at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
13:32:37 E AndroidRuntime : at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
13:32:37 E AndroidRuntime : at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
13:32:37 E AndroidRuntime : at android.view.Choreographer.doCallbacks(Choreographer.java:580)
13:32:37 E AndroidRuntime : at android.view.Choreographer.doFrame(Choreographer.java:550)
13:32:37 E AndroidRuntime : at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
13:32:37 E AndroidRuntime : at android.os.Handler.handleCallback(Handler.java:739)
13:32:37 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:95)
13:32:37 E AndroidRuntime : at android.os.Looper.loop(Looper.java:135)
13:32:37 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:5254)
13:32:37 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
13:32:37 E AndroidRuntime : at java.lang.reflect.Method.invoke(Method.java:372)
13:32:37 E AndroidRuntime : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
13:32:37 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by PaoloRotolo** [comment]
It should work fine.
