### ISSUE TITLE
Date & Time should displayed in local format

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#65]
Date & Time should displayed in local format in the UI but also the date and time input picker should also show those formats.

http://developer.android.com/reference/java/text/SimpleDateFormat.html
http://developer.android.com/reference/java/text/DateFormat.html
http://stackoverflow.com/questions/31692111/date-and-time-format-in-android

**Comment by bkerensa** [comment]
Not fixed

**Comment by satya164** [comment]
In the history view, the date shows as

Sep 28, 2015 01:25:00

Which looks really ugly. It should be displayed as,

Monday, September 28, 2015

(This just adds the day name, changes month to full, and removes time)

And the above should be a group header. The history cards should be grouped by day, and the time should be on the card.

In the time, we should drop the seconds. Nobody cares about seconds precision. Doesn't seem like were storing seconds anyways.

**Comment by satya164** [comment]
https://github.com/Glucosio/android/issues/1#issuecomment-129043214

**Comment by PaoloRotolo** [comment]
I'm currently using Android's system timedate format.

**Comment by satya164** [comment]
Yes, in the example I gave you, the format stays the same, it just adds the day name and makes the month full.

It's exactly how the date is displayed in my pull down notification drawer, plus the year.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?

**Comment by bkerensa** [comment]
This appears fixed @paolorotolo ?
