### ISSUE TITLE
Terms of Use.

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#67]
In Hello we should remove the period behind Terms of Use and maybe consider a Glucosio pink line underneath it.

Lets have @elioqoshi give some design feedback one last time and look at the app for any slight styling advice he might have.

**Comment by satya164** [comment]
Underlines signify text inputs, and it'll make it look bad if we add any kind of underline.

**Comment by satya164** [comment]
@satya164

**Comment by satya164** [comment]
The page has too much spacing and the actual scrollable area is almost half of the entire screen. We should make the scrollable area bigger and make it respond to screen size.

**Comment by PaoloRotolo** [comment]
It should be fine now.

![screenshot_2015-09-27-11-04-24](https://cloud.githubusercontent.com/assets/5623301/10121994/97a8d618-6507-11e5-94a9-95a392d54daf.png)

![screenshot_2015-09-27-11-04-13]

![screenshot_2015-09-27-11-02-58](https://cloud.githubusercontent.com/assets/5623301/10122001/d30413d0-6507-11e5-86c4-34d4a9fe43ec.png)
(https://cloud.githubusercontent.com/assets/5623301/10121995/97b25e5e-6507-11e5-8e51-65adc0098d05.png)

**Comment by satya164** [comment]
Also, momentum scroll is not working in the terms of use scroll view.

**Comment by PaoloRotolo** [comment]
What's momentum scroll?

**Comment by satya164** [comment]
When you scroll fast, and stop, the page doesn't stop scrolling right away. The scroll slows down and eventually stopped. It gives the scroll a natural feeling.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?
