### ISSUE TITLE
Inconsistent fonts across the Application

### ISSUE THREAD

**Issue by satya164** [Glucosio/android#68]
The app has inconsistent fonts. At some places it has Roboto, at some places it has Lato.

Check my comment here https://github.com/facebook/react-native/issues/1167#issuecomment-141730183 on how you set a font for the whole application. It will work for everything and you don't have to extend the textview.

**Comment by PaoloRotolo** [comment]
We're using [Calligraphy](https://github.com/chrisjenx/Calligraphy) to manage fonts in the App. I'll check what happened.

@satya164 Can you tell me exactly where the font look's like Roboto?

**Comment by satya164** [comment]
Hello view, terms of use, tabs, settings etc.

**Comment by PaoloRotolo** [comment]
Fixed in latest daily. Can you confirm?

**Comment by satya164** [comment]
Tabs are still Roboto.

**Comment by satya164** [comment]
Okay, it seems the way calligraphy is being used is wrong. Currently, calligraphy config is being set for each activity separately. Since we need to change the font at the system level, I would propose to create a file `GlucosioApplication.java`, add it to the `android:name` property of the `<application>` field of the `AndroidManifest.xml` file, and do the configuration there.

**Comment by satya164** [comment]
Basically, it will be this,

**GlucosioApplication.java**
```java
import android.app.Application;

public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                        .setDefaultFontPath("fonts/lato.ttf")
                        .setFontAttrId(R.attr.fontPath)
                        .build()
    }

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }
}
```

**AndroidManifest.xml**
```xml
    <application
      ...
      android:name=".GlucosioApplication"
      ...
      >
```

**Comment by PaoloRotolo** [comment]
Fixed. Thanks @satya164!
