### ISSUE TITLE
Empty states look ugly

### ISSUE THREAD

**Issue by satya164** [Glucosio/android#69]
When there is no data, the message which appears on the page is ugly.

The font is too big (try 16sp).

The line height is too big. Every multiline text in the app should have 1.5 line height.

The message isn't aligned to center. Looks like the first line is aligned to center. Hence the whole message looks off center since it's 2 lines on a mobile screen.

It needs to be visually centered too, so we also need to move it a bit to the to again, after vertically centering it, as the appbar and the tab bar are already pushing the content downwards.

**Comment by PaoloRotolo** [comment]
![screenshot_2015-09-27-12-22-54](https://cloud.githubusercontent.com/assets/5623301/10122245/8d9862b4-6512-11e5-975a-75337c358eed.png)

@satya164 what do you think?

**Comment by satya164** [comment]
Need to increase the line height.

**Comment by satya164** [comment]
Also, there should be a curved line pointing towards the FAB

https://github.com/Glucosio/android/issues/1#issuecomment-129043214

**Comment by PaoloRotolo** [comment]
@satya164 @elioqoshi any update on curved line svg?

**Comment by bkerensa** [comment]
Assigning Elio

**Comment by bkerensa** [comment]
Have not heard back from @elioqoshi on this we may need to bump it to Imli

**Comment by elioqoshi** [comment]
Sorry for being late, here we go
https://dl.dropboxusercontent.com/u/62482708/Glucosio/curved%20line%20glucosio.svg

**Comment by PaoloRotolo** [comment]
Thanks @elioqoshi. Adding right now.

**Comment by PaoloRotolo** [comment]
@elioqoshi @satya164 

![screenshot_2015-10-01-19-33-17](https://cloud.githubusercontent.com/assets/5623301/10228506/6aaa260c-6873-11e5-813b-4927958d2892.png)

**Comment by PaoloRotolo** [comment]
@elioqoshi can you please provide another version for landscape layouts?
My Inkscape doesn't want to import the svg well :(

**Comment by bkerensa** [comment]
What format do you need Paolo?

**Comment by PaoloRotolo** [comment]
Same file in .svg but rotated and flipped horizontally.

Also it looks very heavy on tablets. Can we have another thinner version just for screens > 7''?

**Comment by PaoloRotolo** [comment]
UPDATE: Elio is working on it right now.
