### ISSUE TITLE
Tips View

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#7]
Tips (view) to provide general diabetes tips to help users make choices that improve their outcomes.

@PaoloRotolo When you get to working on this lets discuss how this will work early on and I can help source a collection of tips that we can include. And later on perhaps we can make it more expansive.

I think we want to be sensitive about some users being in low bandwidth countries so we should ship some tips local but also have the option to have maybe a RSS feed to add more to the rotation.

**Comment by bkerensa** [comment]
Lets plan on documenting the text for tips at http://wiki.glucosio.org/Tips/Iteration1

**Comment by satya164** [comment]
How do I login there @bkerensa ?

**Comment by PaoloRotolo** [comment]
@satya164: http://wiki.glucosio.org/index.php?title=Special:UserLogin&returnto=Main+Page&type=signup

**Comment by satya164** [comment]
Ignore the text

![5-glucosio-tips](https://cloud.githubusercontent.com/assets/1174278/9427682/9e3d37f6-49a7-11e5-9375-bb6d8026c6a0.png)

**Comment by satya164** [comment]
Ignore the text.

![5-glucosio-tips](https://cloud.githubusercontent.com/assets/1174278/9427690/d81109da-49a7-11e5-8754-a947423f78e2.png)

**Comment by bkerensa** [comment]
Good work :fist:

**Comment by bkerensa** [comment]
@PaoloRotolo Are we making changes here? If so will we be able to do it by the string freeze on the 14th?

**Comment by PaoloRotolo** [comment]
@bkerensa We need to decide another name for Tips: "Assistant" or "Notifications"?. Then create some specific tabs that requires user interaction like "Insert your height"...

**Comment by bkerensa** [comment]
@PaoloRotolo Assistant will work. Do you need a new mockup from @satya164 for this?

**Comment by PaoloRotolo** [comment]
Hmm, I think I can make something even without mockup.
I need some actions we want to add: "Add weight, height" and?

**Comment by bkerensa** [comment]
@PaoloRotolo Lets do:

Add weight
Add height
Select target range (remember ADA, AACE, UK Nice etc)
Opt-in to help research


Can we have also have a action to add blood glucose twice daily? And maybe make it trigger a notification? Is this too much work to be done by string freeze if so we can push that off.

**Comment by PaoloRotolo** [comment]
Isn't Opt-in in HelloActivity?

**Comment by bkerensa** [comment]
It is but its optional so we can use Assistant to have a dismissible action as kind of a second chance to offer them to opt-in but ofc they can do this in settings too. I have asked Priyanka to share ideas for more actions and will get Elio too.

**Comment by elioqoshi** [comment]
Shouldn't it be opt-in on default and opt-out available in settings?

**Comment by bkerensa** [comment]
@elioqoshi Well the checkbox is by default checked but they can uncheck it in hello but the assistant might make an extra case for filling it in.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?
