### ISSUE TITLE
Make Gitty Layout Match Glucosio 

### ISSUE THREAD

**Issue by satya164** [Glucosio/android#70]
Gitty looks alien compared to rest of the app.

It should have a actionbar with back button.

I should be able to edit the device info that's being sent.

Password field in GH login is in monospace font (?)

Also, instead of entering username and password, can we use oAuth?

Also, I couldn't report any bugs. I tried both logging in and checking I don't have any account.

**Comment by satya164** [comment]
Also, it wastes a lot of space.

**Comment by bkerensa** [comment]
Yeah it would be nice if we could have Gitty use oauth and maybe use Glucat to file the bug
having people create a GH account could be a barrier.

**Comment by bkerensa** [comment]
@PaoloRotolo is this fixed?

**Comment by PaoloRotolo** [comment]
Gitty works well in latest commit.
@bkerensa now you can just select "I don't have an account" and Glucat will report the bug for you.

About design, I guess we have to make changes in my library to add custom layouts support.
Can we postpone design for 0.8.x?

**Comment by bkerensa** [comment]
@PaoloRotolo Yes but lets reopen and mark this for that.

**Comment by rotolonico** [comment]
I'm working on it...

**Comment by PaoloRotolo** [comment]
@elioqoshi @satya164 Can you please find 4 colors (backgrond1, backgrond2, FAB1, FAB2) that fit with Glucosio palette?
