### ISSUE TITLE
Update Any Remaining Code to ActiveAndroid

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#73]
@PaoloRotolo Can you list here any remaining bits that need upgrading so Chris has a list

**Comment by PaoloRotolo** [comment]
getGlucoseReadingsForLastMonthAsArray()
getAverageGlucoseReadingsByWeek()
getAverageGlucoseReadingsByMonth()

@chrispecoraro I've made 3 methods that can help you:
you can call them from DatabaseHandler with
getGlucoseReadings(String where), getGlucoseReadings(String where, Object args) and getGlucoseReadings(String where, Object args, String[] columns).

**Comment by bkerensa** [comment]
Christopher says this is done.... Closing!
