### ISSUE TITLE
non-translatable strings in strings.xml

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#79]
@string/helloactivity_spinner_preferred_range_1 is being improted in Crowdin as translatable.... Can you make sure its not? Not sure how you did this before but I believe there was a fix to mark some strings as not translatable.

**Comment by bkerensa** [comment]
If not I have went ahead and manually hid them on the l10n platform

**Comment by PaoloRotolo** [comment]
Just add ```translatable="false``` in strings.xml, like:

```
    <string name="helloactivity_spinner_preferred_range_1" translatable="false">ADA</string>
```
