### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#8]
We will need a SQLite DB and also to ensure that Android M native app backup occurs between flashes and when users change hardware see: https://developer.android.com/preview/backup/index.html)

Edit this to add any remaining DB work this will track it for Noce!

**Comment by bkerensa** [comment]
@ahhmarr We are aiming for wrap up by the 14th so this bug is tracking final DB changes.

@PaoloRotolo feel free to update this with any remaining DB work you need for us to ship.

**Comment by PaoloRotolo** [comment]
Things left to do are here: http://wiki.glucosio.org/Planning/database_model

**Comment by PaoloRotolo** [comment]
Ahmar just pushed the updates.
