### ISSUE TITLE
When phone horizontal the line svg looks odd

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/android#81]
So the new line is nice but on my Nexus 6 in horizontal it looks weird.

**Comment by PaoloRotolo** [comment]
I know, @elioqoshi sent me a another .svg for landscape mode on Telegram.
Unfortunately Telegram seems down right now. I'll update it as soon as it gets up again.

**Comment by PaoloRotolo** [comment]
Fixed in latest revision.
