### ISSUE TITLE
GITTY test

### ISSUE THREAD

**Issue by glucat** [Glucosio/android#84]
test

Debug info:
 OS Version: 3.4.42-g32473a7(2dbf45e7e7)
 OS API Level: 22
 Device: falcon_umts
 Model (and Product): Moto G (cm_falcon)
 RELEASE: 5.1.1
 BRAND: motorola
 DISPLAY: cm_falcon-userdebug 5.1.1 LVY48F 2dbf45e7e7 test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 Build ID: LVY48F
 MANUFACTURER: motorola
 SERIAL: TA0680059E
 USER: jenkins
 HOST: cyanogenmod

Extra Info: Nothing to show.

**Comment by PaoloRotolo** [comment]
Yay, it works.
