### ISSUE TITLE
Gitty test

### ISSUE THREAD

**Issue by glucat** [Glucosio/android#93]
Test gitty before release.

Debug info:
 OS Version: 3.4.0-ga5a4133(2256973)
 OS API Level: 23
 Device: flo
 Model (and Product): Nexus 7 (razor)
 RELEASE: 6.0
 BRAND: google
 DISPLAY: MRA58K
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: flo
 Build ID: MRA58K
 MANUFACTURER: asus
 SERIAL: 07a4214c
 USER: android-build
 HOST: vpak15.mtv.corp.google.com

Extra Info: Nothing to show.

**Comment by PaoloRotolo** [comment]
Cool, new token works.
