### ISSUE TITLE
It's hard to configure the app

### ISSUE THREAD

**Issue by glucat** [Glucosio/android#96]
Specially when trying to get the right max and min glucose, using the standard systems are just alien to me. 

Debug info:
 OS Version: 3.10.20-262977-gdb13b6f(WW_a501cg-WW_user_2.22.40.54_20150527_44-user-20150527)
 OS API Level: 19
 Device: ASUS_T00J1
 Model (and Product): ASUS_T00J (WW_a501cg)
 RELEASE: 4.4.2
 BRAND: asus
 DISPLAY: ASUS_T00J_WW_user_2.22.40.54_20150527_44 release-keys
 CPU_ABI: x86
 CPU_ABI2: armeabi-v7a
 HARDWARE: redhookbay
 Build ID: KVT49L
 MANUFACTURER: asus
 SERIAL: f1azb6005415
 USER: jenkins
 HOST: ReleaseServer

Extra Info: Nothing to show.

**Comment by bkerensa** [comment]
@PaoloRotolo this might not have enough information to be useful for us and its anonymous so we cannot even ask for more info.

**Comment by bkerensa** [comment]
Not enough information to work on this
